### PR TITLE
this is the correct pull request

### PR DESCRIPTION
**Pull request by seandepagnier**

### CODE REVIEW

**Comment by seandepagnier** [comment]
from what I can tell pypilot doesnt really work without this.

**Comment by sailoog** [comment]
sorry for the delay

pypilot works ok right now in openplotter. There is something weird, you may not have the last version of the openplotter-pypilot code because you are sending code that already exist in the same file. The only thing that does not exist is adding dev/ttyAMA0 by default but that is intentional because there are people only using the IMU mode who also uses that interface for others devices.

In the other hand I notified you here that I was adding the services in openplotter code: https://forum.openmarine.net/showthread.php?tid=4221&pid=24216#pid24216 The user pi is hardcoded in the pypilot scripts.

There are some changes like the pypilot restarts at the startup that I can apply but I am afraid I can not merge your PR. I will do some changes in a new PR with some of your changes and this one: https://forum.openmarine.net/showthread.php?tid=4335&pid=24334#pid24334

**Comment by seandepagnier** [comment]
I will try again to make a pull request easier for you to merge.   It is broken without these changes and.. no it doesnt work ok.

**Comment by sailoog** [comment]
It is working right for me. Let's see if we can find out what is wrong in your system in the new PR

**Pull request closed without merging**
